// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htucmuizfvoctddclbfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dWNtdWl6ZnZvY3RkZGNsYmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDIzODIsImV4cCI6MjA1NTU3ODM4Mn0.8ctFcUvMxO-W0twq-lEDGxbSB4P0oYmtJe5j2mNzaYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);